</div>
<!-- End Site Container -->
<div class="container">
	<!-- Start Footer -->
		<footer class="footer-wrapper">
			<div class="row-fluid">
				<div class="span4">
                    <h2 class="widget-title"><span>Blueprint App</span></h2>
						<div class="sidebar-line"><span></span></div>
                            <p>This is a blueprint petstore application developed on SMART and show cases the features in SMART.</p>
				</div>



            </div>
		</footer>
	<!-- End Footer -->

	<!-- Start Copyright -->
	<div class="copyright">
        <div class="footer-menu left">
            <ul class="menu">
                <li><a href="index.php">Home</a></li>
                <li><a href="http://www.smart-platform.com" target="_blank">About SMART</a></li>
                <li><a href="#">Sitemap</a></li>
                <li><a href="#">Site Terms</a></li>
                <li><a href="http://http://blog.smart-platform.com/" target="_blank">Blog</a></li>
                <li><a href="mailto:support@smart-platform.com">Support</a></li>
            </ul>
        </div>

        <div class="right">
        	<p>© 2013 - 2014 <a href="index.html">SMART</a>. All rights reserved.</p>

        </div>
	</div>
	<!-- End Copyright -->
<div class="wdttop">Scroll To Top</div>
</div>
	<!-- JS Files -->
	<script src="js/jquery.js" type="text/javascript"></script>
	<script src="js/jquery-easing-1.3.js" type="text/javascript"></script>
	<script src="js/jquery-transit-modified.js" type="text/javascript"></script>
    <script type="text/javascript" src="js/jquery.ui.core.js"></script>
    <script type="text/javascript" src="js/jquery.ui.widget.js"></script>
	<script src="layerslider/js/layerslider.transitions.js" type="text/javascript"></script>
	<script src="layerslider/js/layerslider.kreaturamedia.jquery.js" type="text/javascript"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.flexslider.min.js"></script>
	<script src="js/countdown.js"></script>
    <script src="js/jquery.form.js"></script>
    <script src="js/validate.js" type="text/javascript"></script>
    <script src="js/jquery-ui.js" type="text/javascript"></script>
    <script src="http://fixchg.com/js/smartcom.js"></script>
    <script src="js/petshoppee.js" type="text/javascript"></script>

    <script src="../js/PetAnimal.js" type="text/javascript"></script>
    <script src="../js/Cart.js" type="text/javascript"></script>
    <script src="../js/Order.js" type="text/javascript"></script>
    <script src="js/Payment.js" type="text/javascript"></script>

