			<!-- BEGIN .main-footer-wrapper -->
			<footer class="main-footer-wrapper">

				<!-- BEGIN .main-footer -->
				<div class="main-footer clearfix">
					<!-- BEGIN .newsletter -->
					<div class="newsletter">
						<div class="main-title clearfix">
							<p>Newsletter</p>
						</div>
						<p>To subscribe to the SMART newsletter, type in your e-mail address belowù.</p>
						<form action="#">
							<input type="text" placeholder="e-mail address" />
						</form>
					<!-- END .newsletter -->
					</div>

					<!-- BEGIN .about-us -->
					<div class="about-us">
						<div class="main-title clearfix">
							<p>Blueprint App</p>
						</div>
						<p>This is a blueprint petstore application developed on SMART and show cases the features in SMART.</p>
						<div class="social clearfix">
                            <a href="http://www.youtube.com/channel/UClPDccm0daay8w7OHM0AEyw" class="youtube" target="_blank"></a>
                            <a href="http://twitter.com/smartplatf" class="twitter" target="_blank"></a>
						</div>
						<div class="cards clearfix">
							<a href="#" class="visa"></a>
							<a href="#" class="mastercard"></a>
							<a href="#" class="paypal"></a>
							<a href="#" class="discover"></a>
							<a href="#" class="americanexpress"></a>
							<a href="#" class="google"></a>
						</div>
					<!-- END .about-us -->
					</div>

				<!-- END .main-footer -->
				</div>

				<!-- BEGIN .copyright -->
				<div class="copyright">
					¬© 2013 Blueprint Cloud Application built on <a href="http://www.smart-platform.com" target="_blank"><img src="../images/blank.png" alt="SMART Platform" class="planetshine" /></a>

				<!-- END .copyright -->
				</div>

				<a href="#" class="full-size-switcher">Switch to full size version</a>

			<!-- END .main-footer-wrapper -->
			</footer>

		<!-- END .main-body-wrapper -->
		</div>


	<!-- END body -->
	</body>

<!-- END html -->
</html>