<!-- BEGIN .quick-shop -->
<div class="quick-shop clearfix">
    <div class="content clearfix">

        <div class="item-block-1">
            <div class="image-wrapper" id="_quick-shop-product-slider">
                <div class="image">
                    <a href="#"><img src="../images/photos/photo-11.jpg" alt="" id="quickshopimage"/></a>
                </div>
            </div>
        </div>

        <div class="main-item">
            <div class="item-info">
                <h2><a href="#" id="quickshophead">This should be replaced</a></h2>
                <p class="item-text" id="quickshoptext">
                    This should be replaced
                </p>
                <div class="details clearfix">
                    <form action="#">
                        <input type="hidden" id="shopItemId" name="shopItemId"/>
                        <p class="item quantity">
                            <label>Quantity:</label>
                            <select>
                                <option>1</option>
                            </select>
                        </p>
                        <p class="item">
                            <label>Share this item:</label>
                            <span class="social-icons clearfix">
                                <span class='st_facebook_custom facebook'></span>
                                <span class='st_twitter_custom twitter'></span>
                            </span>
                        </p>
                    </form>
                </div>
                <div class="price" id="quickshopprice">
                    $0.00
                </div>
                <div class="buy">
                    <button type="button" id="addtocart">Add to cart</button>
                </div>
            </div>
        </div>

        <a href="#" class="close"></a>

    </div>
<!-- END .quick-shop -->
</div>